# CREACION DE LOS USUARIOS #

CREATE USER 'johan'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'felipe'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'josias'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'alfonso'@'localhost' IDENTIFIED BY '1234';

# DAR TODOS LOS PRIVILEGIOS A LOS USUARIOS #


GRANT ALL PRIVILEGES ON *.* TO 'johan'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'felipe'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'josias'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'alfonso'@'localhost' WITH GRANT OPTION;

# ACTUALIZAR PRIVILEGIOS #

FLUSH PRIVILEGES;
