# CREACION DE LOS USUARIOS #
CREATE USER 'cineroadmap'@'localhost' IDENTIFIED BY '1234';

# DAR TODOS LOS PRIVILEGIOS A LOS USUARIOS #
GRANT ALL PRIVILEGES ON *.* TO 'cineroadmap'@'localhost' WITH GRANT OPTION;

# ACTUALIZAR PRIVILEGIOS #

FLUSH PRIVILEGES;
