@startuml
title Diagrama de Bloques - CineRoadmap

package "resources" {
    [img]
    [db]
    [css]
    [diagramas]
}

package "app"{
    package "Vista" {
    }

    package "Controlador" {
    }

    package "Modelo" {
    }

    package "Util" {

    }
}

package "Librerías externas"


' Relaciones principales]
[resources] --> [app]
[Util] --> [Vista]
[Util] --> [Controlador]
[Modelo] <--> [Vista]
[Modelo] <--> [Controlador]
[Vista] --> [Controlador]
[Librerías externas] --> [app]
@enduml
